---
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.6
  UseCache: true
  NewCops: enable
  Exclude:
    - '**/*.gemspec'

##
# Disable items that may require a Ruby > 2.0, our minimum supported version.
# When we can comfortably require Ruby >= 2.6 (version 4.x), these can be
# enabled.
Style/ExpandPathArguments:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false
##

##
# There are cases where Rubocop's default is just wrong to my eyes of having
# used Ruby for the last twenty years. Sometimes, we just disable the cop
# because it doesn't offer any useful configuration. Where we can, we change
# the configuration. Where we can't, we disable.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%I': ()
    '%w': ()
    '%W': ()

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/HashAlignment:
  EnforcedColonStyle: key
  EnforcedHashRocketStyle: key
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: compact

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  EnforcedStyle: kind_of?

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/Copyright:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Encoding: # For a gem that is using Ruby 1.9, change this to true.
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/mime-types-data.rb

Style/FormatString:
  EnforcedStyle: percent

Style/MultilineBlockChain:
  Enabled: false


Style/ParallelAssignment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false

##
# Disable all of the stupid hobgoblins

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# End of hobgoblins
##
